name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change 'main' to your default branch if different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload files to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./  # Directory to upload, where your index.html resides

  pages:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
